plugins {
    id 'com.android.application'
}

import java.text.SimpleDateFormat
import java.util.Date
import java.util.TimeZone

def buildVersionName = new SimpleDateFormat('yyyy.MM.dd.HHmm', Locale.US).format(new Date())

android {
    namespace 'com.example.simplebrowser'
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId 'com.example.simplebrowser'
        minSdk 19
        targetSdk 35
        versionCode 4
        versionName buildVersionName
    }
}
