package com.example.simplebrowser;

import android.webkit.JavascriptInterface;

/**
 * Narrow bridge for actions on the built-in Profiles page.
 *
 * The page itself is generated by Simple Browser, so switching profiles
 * directly through this bridge avoids depending on WebView's navigation
 * callback ordering. Navigation URLs remain as a fallback for older builds.
 */
public final class ProfileActionBridge {

    private final MainActivity activity;
    private final BrowserTab tab;

    public ProfileActionBridge(
            MainActivity activity,
            BrowserTab tab) {
        this.activity = activity;
        this.tab = tab;
    }

    @JavascriptInterface
    public void switchProfile(
            final String profileId) {

        if (activity == null ||
                tab == null ||
                !tab.profilesPage ||
                profileId == null ||
                profileId.trim().isEmpty()) {
            return;
        }

        activity.runOnUiThread(
                () -> activity.switchProfile(
                        profileId.trim()));
    }
}
